name: On GitHub Tag, Docker Build and Push

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Get variables from GitHub
        id: git_vars
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Configure Docker
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Tag and Push
        run: |
          docker build . --tag ghcr.io/$GITHUB_REPOSITORY:latest
          docker tag ghcr.io/$GITHUB_REPOSITORY:latest ghcr.io/$GITHUB_REPOSITORY:${{ steps.git_vars.outputs.TAG }}
          docker push ghcr.io/$GITHUB_REPOSITORY:latest
          docker push ghcr.io/$GITHUB_REPOSITORY:${{ steps.git_vars.outputs.TAG }}
